#!/bin/sh

cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd

rm ./content1.zip
rm ./content2.zip
rm ./content3.zip
rm ./content4.zip
rm ./content5.zip
rm ./content6.zip

zip -er content1.zip ./Content1
zip -er content2.zip ./Content2
zip -er content3.zip ./Content3
zip -er content4.zip ./Content4
zip -er content5.zip ./Content5
zip -er content6.zip ./Content6
